### ISSUE TITLE
Error: transition superseded and other errors in Console

### ISSUE THREAD

**Issue by pankrats** [trezor/stellar-account-viewer#1]
I get these errors in Console when I open https://trezor.io/stellar/#!/

<img width="1161" alt="screen shot 2018-12-05 at 15 17 11" src="https://user-images.githubusercontent.com/31442634/49519285-ed084c80-f8a0-11e8-96bd-d8884010a339.png">

**Comment by prusnak** [comment]
I guess this is harmless.
